from __future__ import annotations

from datetime import date
from pathlib import Path
from tempfile import TemporaryDirectory

from docx import Document
from docx.enum.section import WD_SECTION
from docx.enum.table import (
    WD_CELL_VERTICAL_ALIGNMENT,
    WD_TABLE_ALIGNMENT,
)
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor

from artifacts.charting import render_chart_image
from artifacts.equations import (
    EquationRenderingError,
    render_equation_image,
)
from artifacts.models import (
    ArtifactDocument,
    ArtifactSection,
    BulletListBlock,
    CalloutBlock,
    ChartBlock,
    CodeBlock,
    DiagramBlock,
    EquationBlock,
    PageBreakBlock,
    ParagraphBlock,
    QuoteBlock,
    TableBlock,
)


def _set_cell_shading(
    cell,
    fill: str,
) -> None:
    properties = cell._tc.get_or_add_tcPr()
    shading = properties.find(qn("w:shd"))

    if shading is None:
        shading = OxmlElement("w:shd")
        properties.append(shading)

    shading.set(qn("w:fill"), fill)


def _set_repeat_table_header(row) -> None:
    properties = row._tr.get_or_add_trPr()
    header = OxmlElement("w:tblHeader")
    header.set(qn("w:val"), "true")
    properties.append(header)


def _add_field(
    paragraph,
    instruction: str,
    placeholder: str = "",
) -> None:
    run = paragraph.add_run()

    begin = OxmlElement("w:fldChar")
    begin.set(qn("w:fldCharType"), "begin")

    instruction_text = OxmlElement("w:instrText")
    instruction_text.set(
        qn("xml:space"),
        "preserve",
    )
    instruction_text.text = instruction

    separate = OxmlElement("w:fldChar")
    separate.set(qn("w:fldCharType"), "separate")

    visible_text = OxmlElement("w:t")
    visible_text.text = placeholder

    end = OxmlElement("w:fldChar")
    end.set(qn("w:fldCharType"), "end")

    run._r.extend(
        [
            begin,
            instruction_text,
            separate,
            visible_text,
            end,
        ]
    )


def _configure_document(
    document: Document,
    artifact: ArtifactDocument,
) -> None:
    section = document.sections[0]

    section.page_width = Inches(8.27)
    section.page_height = Inches(11.69)
    section.top_margin = Inches(0.78)
    section.bottom_margin = Inches(0.72)
    section.left_margin = Inches(0.82)
    section.right_margin = Inches(0.82)

    document.core_properties.title = artifact.title
    document.core_properties.author = (
        artifact.author
        or "Authentic AI"
    )
    document.core_properties.subject = (
        artifact.subtitle
        or "Professional generated artifact"
    )
    document.core_properties.comments = (
        "Generated by Authentic AI Artifact Studio"
    )

    styles = document.styles

    normal = styles["Normal"]
    normal.font.name = "Aptos"
    normal.font.size = Pt(10.5)
    normal.font.color.rgb = RGBColor(
        36,
        43,
        56,
    )
    normal.paragraph_format.space_after = Pt(7)
    normal.paragraph_format.line_spacing = 1.12

    title = styles["Title"]
    title.font.name = "Aptos Display"
    title.font.size = Pt(28)
    title.font.bold = True
    title.font.color.rgb = RGBColor(
        23,
        32,
        51,
    )

    subtitle = styles["Subtitle"]
    subtitle.font.name = "Aptos"
    subtitle.font.size = Pt(14)
    subtitle.font.italic = True
    subtitle.font.color.rgb = RGBColor(
        85,
        96,
        114,
    )

    for style_name, size in (
        ("Heading 1", 18),
        ("Heading 2", 14),
        ("Heading 3", 12),
    ):
        style = styles[style_name]
        style.font.name = "Aptos Display"
        style.font.size = Pt(size)
        style.font.bold = True
        style.font.color.rgb = RGBColor(
            23,
            32,
            51,
        )
        style.paragraph_format.space_before = Pt(12)
        style.paragraph_format.space_after = Pt(6)
        style.paragraph_format.keep_with_next = True

    caption = styles["Caption"]
    caption.font.name = "Aptos"
    caption.font.size = Pt(8.5)
    caption.font.italic = True
    caption.font.color.rgb = RGBColor(
        99,
        108,
        124,
    )

    header = section.header.paragraphs[0]
    header.text = artifact.title[:75]
    header.alignment = WD_ALIGN_PARAGRAPH.RIGHT

    if header.runs:
        header.runs[0].font.name = "Aptos"
        header.runs[0].font.size = Pt(8)
        header.runs[0].font.color.rgb = RGBColor(
            100,
            109,
            125,
        )

    footer = section.footer.paragraphs[0]
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER

    footer_run = footer.add_run(
        "Authentic AI  |  Page "
    )
    footer_run.font.name = "Aptos"
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(
        100,
        109,
        125,
    )

    _add_field(
        footer,
        "PAGE",
        "1",
    )

    settings = document.settings.element
    update_fields = OxmlElement("w:updateFields")
    update_fields.set(qn("w:val"), "true")
    settings.append(update_fields)


def _add_cover(
    document: Document,
    artifact: ArtifactDocument,
) -> None:
    for _ in range(7):
        document.add_paragraph()

    title = document.add_paragraph()
    title.style = document.styles["Title"]
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title.add_run(artifact.title)

    if artifact.subtitle:
        subtitle = document.add_paragraph()
        subtitle.style = document.styles["Subtitle"]
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        subtitle.add_run(artifact.subtitle)

    divider = document.add_paragraph()
    divider.alignment = WD_ALIGN_PARAGRAPH.CENTER

    divider_run = divider.add_run(
        "━━━━━━━━━━━━━━━━━━━━"
    )
    divider_run.font.color.rgb = RGBColor(
        170,
        179,
        194,
    )
    divider_run.font.size = Pt(11)

    metadata = document.add_paragraph()
    metadata.alignment = WD_ALIGN_PARAGRAPH.CENTER

    author_run = metadata.add_run(
        artifact.author
        or "Authentic AI"
    )
    author_run.bold = True
    author_run.font.name = "Aptos"
    author_run.font.size = Pt(10)

    date_run = metadata.add_run(
        "\n"
        + date.today().strftime(
            "%B %d, %Y"
        )
    )
    date_run.font.name = "Aptos"
    date_run.font.size = Pt(9)
    date_run.font.color.rgb = RGBColor(
        105,
        115,
        134,
    )

    document.add_page_break()


def _add_contents(
    document: Document,
) -> None:
    document.add_heading(
        "Contents",
        level=1,
    )

    paragraph = document.add_paragraph()

    _add_field(
        paragraph,
        r'TOC \o "1-3" \h \z \u',
        (
            "Open this file in Microsoft Word "
            "or LibreOffice and update fields "
            "to populate the table of contents."
        ),
    )

    document.add_page_break()


def _add_table(
    document: Document,
    block: TableBlock,
) -> None:
    table = document.add_table(
        rows=1,
        cols=len(block.columns),
    )

    table.style = "Table Grid"
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.autofit = True

    header_row = table.rows[0]
    _set_repeat_table_header(header_row)

    for index, column in enumerate(
        block.columns
    ):
        cell = header_row.cells[index]
        cell.text = column
        cell.vertical_alignment = (
            WD_CELL_VERTICAL_ALIGNMENT.CENTER
        )

        _set_cell_shading(
            cell,
            "E9EDF4",
        )

        paragraph = cell.paragraphs[0]
        paragraph.alignment = (
            WD_ALIGN_PARAGRAPH.LEFT
        )

        for run in paragraph.runs:
            run.bold = True
            run.font.name = "Aptos"
            run.font.size = Pt(9.5)
            run.font.color.rgb = RGBColor(
                23,
                32,
                51,
            )

    for row_values in block.rows:
        cells = table.add_row().cells

        for index, value in enumerate(
            row_values
        ):
            cell = cells[index]
            cell.text = value
            cell.vertical_alignment = (
                WD_CELL_VERTICAL_ALIGNMENT.TOP
            )

            paragraph = cell.paragraphs[0]

            for run in paragraph.runs:
                run.font.name = "Aptos"
                run.font.size = Pt(9.2)

    if block.caption:
        caption = document.add_paragraph(
            block.caption
        )
        caption.style = document.styles[
            "Caption"
        ]
        caption.alignment = (
            WD_ALIGN_PARAGRAPH.CENTER
        )


def _add_code_block(
    document: Document,
    block: CodeBlock,
) -> None:
    paragraph = document.add_paragraph()
    paragraph.paragraph_format.space_before = Pt(5)
    paragraph.paragraph_format.space_after = Pt(9)

    paragraph_properties = (
        paragraph._p.get_or_add_pPr()
    )

    shading = OxmlElement("w:shd")
    shading.set(qn("w:fill"), "F5F7FA")
    paragraph_properties.append(shading)

    borders = OxmlElement("w:pBdr")
    border = OxmlElement("w:top")
    border.set(qn("w:val"), "single")
    border.set(qn("w:sz"), "4")
    border.set(qn("w:color"), "D5DAE3")
    borders.append(border)
    paragraph_properties.append(borders)

    run = paragraph.add_run(block.code)
    run.font.name = "Courier New"
    run.font.size = Pt(8.8)



def _add_diagram_block(
    document: Document,
    block: DiagramBlock,
) -> None:
    if block.title:
        caption = document.add_paragraph(block.title)
        caption.style = document.styles["Caption"]
        caption.alignment = WD_ALIGN_PARAGRAPH.CENTER

    table = document.add_table(
        rows=max(1, len(block.steps)),
        cols=2,
    )
    table.style = "Table Grid"

    for index, step in enumerate(block.steps):
        number_cell = table.cell(index, 0)
        text_cell = table.cell(index, 1)
        number_cell.text = str(index + 1)
        text_cell.text = step
        number_cell.width = Inches(0.55)

        for cell in (number_cell, text_cell):
            properties = cell._tc.get_or_add_tcPr()
            shading = OxmlElement("w:shd")
            shading.set(qn("w:fill"), "F3F8F6")
            properties.append(shading)


def _add_equation_block(
    document: Document,
    block: EquationBlock,
    *,
    image_path: Path,
) -> None:
    paragraph = document.add_paragraph()
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    paragraph.paragraph_format.space_before = Pt(6)
    paragraph.paragraph_format.space_after = Pt(8)

    if block.label:
        label = paragraph.add_run(f"{block.label}\n")
        label.bold = True

    try:
        pixel_width, pixel_height = (
            render_equation_image(
                block.expression,
                image_path,
            )
        )
        aspect_ratio = pixel_width / pixel_height
        image_width_inches = min(
            6.0,
            max(1.6, aspect_ratio * 0.48),
        )
        paragraph.add_run().add_picture(
            str(image_path),
            width=Inches(image_width_inches),
        )
    except EquationRenderingError:
        expression = paragraph.add_run(block.expression)
        expression.font.name = "Cambria Math"
        expression.font.size = Pt(11)

def _add_section(
    document: Document,
    section: ArtifactSection,
    *,
    chart_directory: Path,
    chart_counter: list[int],
) -> None:
    document.add_heading(
        section.title,
        level=min(
            max(section.level, 1),
            3,
        ),
    )

    for block in section.blocks:
        if isinstance(block, ParagraphBlock):
            document.add_paragraph(
                block.text
            )
        elif isinstance(block, QuoteBlock):
            paragraph = document.add_paragraph()
            paragraph.style = document.styles["Quote"]
            run = paragraph.add_run(block.text)
            run.italic = True

        elif isinstance(block, CalloutBlock):
            paragraph = document.add_paragraph()
            properties = paragraph._p.get_or_add_pPr()
            shading = OxmlElement("w:shd")
            shading.set(qn("w:fill"), "F1F7F5")
            properties.append(shading)
            title_run = paragraph.add_run(
                f"{block.title}\n"
            )
            title_run.bold = True
            paragraph.add_run(block.text)


        elif isinstance(block, BulletListBlock):
            style_name = (
                "List Number"
                if block.ordered
                else "List Bullet"
            )

            for item in block.items:
                paragraph = document.add_paragraph(
                    item,
                    style=style_name,
                )
                paragraph.paragraph_format.space_after = Pt(3)

        elif isinstance(block, TableBlock):
            _add_table(
                document,
                block,
            )

        elif isinstance(block, ChartBlock):
            chart_counter[0] += 1

            image_path = (
                chart_directory
                / f"chart-{chart_counter[0]}.png"
            )

            render_chart_image(
                block,
                image_path,
            )

            image_paragraph = document.add_paragraph()
            image_paragraph.alignment = (
                WD_ALIGN_PARAGRAPH.CENTER
            )

            image_run = image_paragraph.add_run()
            image_run.add_picture(
                str(image_path),
                width=Inches(6.2),
            )

            caption = document.add_paragraph(
                block.caption
                or block.title
            )
            caption.style = document.styles[
                "Caption"
            ]
            caption.alignment = (
                WD_ALIGN_PARAGRAPH.CENTER
            )

        elif isinstance(block, DiagramBlock):
            _add_diagram_block(document, block)

        elif isinstance(block, EquationBlock):
            chart_counter[0] += 1
            equation_path = (
                chart_directory
                / f"equation-{chart_counter[0]}.png"
            )
            _add_equation_block(
                document,
                block,
                image_path=equation_path,
            )

        elif isinstance(block, PageBreakBlock):
            document.add_page_break()

        elif isinstance(block, CodeBlock):
            _add_code_block(
                document,
                block,
            )


def render_docx(
    artifact: ArtifactDocument,
    output_path: Path,
) -> Path:
    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    document = Document()

    _configure_document(
        document,
        artifact,
    )

    _add_cover(
        document,
        artifact,
    )

    _add_contents(document)

    with TemporaryDirectory(
        prefix="authentic-docx-charts-",
    ) as temporary_directory:
        chart_directory = Path(
            temporary_directory
        )

        chart_counter = [0]

        for section in artifact.sections:
            _add_section(
                document,
                section,
                chart_directory=chart_directory,
                chart_counter=chart_counter,
            )

        document.save(output_path)

    if (
        not output_path.exists()
        or output_path.stat().st_size <= 0
    ):
        raise RuntimeError(
            "DOCX rendering failed."
        )

    return output_path